package repo_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/Sawmonabo/agent-brain/internal/provider"
	"github.com/Sawmonabo/agent-brain/internal/provider/providertest"
	"github.com/Sawmonabo/agent-brain/internal/repo"
)

func testRegistry(t *testing.T) *provider.Registry {
	t.Helper()
	claude := providertest.New("claude", provider.ScopePerProject, []provider.Pattern{
		{Glob: "MEMORY.md", Class: provider.ClassDerivedIndex},
		{Glob: "*.md", Class: provider.ClassFact},
	})
	codex := providertest.New("codex", provider.ScopeGlobal, []provider.Pattern{
		{Glob: "raw_memories.md", Class: provider.ClassFact},
		{Glob: "memory_summary.md", Class: provider.ClassRegenerated},
		{Glob: "MEMORY.md", Class: provider.ClassRegenerated},
		{Glob: "rollout_summaries/*", Class: provider.ClassRegenerated},
	})
	reg, err := provider.NewRegistry(claude, codex)
	if err != nil {
		t.Fatal(err)
	}
	return reg
}

// TestGenerateAttributesGolden pins the exact canonical file. Ordering is
// load-bearing three ways: gitattributes resolves per attribute with the
// LAST matching line winning, so the '*' default comes first, lww
// overrides follow, and the meta/self exclusions come last (they must
// beat everything). The default and exclusion lines are byte-identical
// with the e2e harness const — continuity of the proven wiring.
func TestGenerateAttributesGolden(t *testing.T) {
	t.Parallel()
	want := `# Generated by agent-brain; do not edit (init/doctor rewrite this file).
* filter=agentbrain diff=agentbrain merge=agentbrain -text
**/codex/memory_summary.md merge=agentbrain-lww
**/codex/MEMORY.md merge=agentbrain-lww
**/codex/rollout_summaries/* merge=agentbrain-lww
.gitattributes -filter -diff -merge text eol=lf
.agent-brain/** -filter -diff -merge text eol=lf
`
	got := repo.GenerateAttributes(testRegistry(t))
	if diff := cmp.Diff(want, got); diff != "" {
		t.Fatalf("GenerateAttributes mismatch (-want +got):\n%s", diff)
	}
	// Determinism: byte-identical on repeat (no map-order leakage).
	if again := repo.GenerateAttributes(testRegistry(t)); again != got {
		t.Fatal("GenerateAttributes is nondeterministic")
	}
}

func TestWriteAttributes(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	l := repo.NewLayout(root)
	if err := repo.WriteAttributes(l, testRegistry(t)); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(root, ".gitattributes"))
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != repo.GenerateAttributes(testRegistry(t)) {
		t.Fatal("written attributes differ from generated content")
	}
	// Idempotent overwrite (renameio replace, not append).
	if err := repo.WriteAttributes(l, testRegistry(t)); err != nil {
		t.Fatal(err)
	}
	again, err := os.ReadFile(filepath.Join(root, ".gitattributes"))
	if err != nil {
		t.Fatal(err)
	}
	if string(again) != string(data) {
		t.Fatal("rewrite is not idempotent")
	}
}
