package repo

import (
	"fmt"
	"strings"

	"github.com/google/renameio/v2"

	"github.com/Sawmonabo/agent-brain/internal/provider"
)

// GenerateAttributes emits the canonical .gitattributes for a memories
// repo (spec §5). Line order is load-bearing: gitattributes resolves
// each attribute with the LAST matching line winning, so the filtered
// default comes first, per-provider newest-wins overrides follow, and
// the self/meta exclusions close the file so nothing re-filters them.
// The default and exclusion lines are byte-identical with the wiring the
// e2e suite proved.
//
// Inputs are pre-validated (provider.NewRegistry rejects names and globs
// that cannot appear in an attributes line), so this function is total.
func GenerateAttributes(reg *provider.Registry) string {
	var b strings.Builder
	b.WriteString("# Generated by agent-brain; do not edit (init/doctor rewrite this file).\n")
	b.WriteString("* filter=agentbrain diff=agentbrain merge=agentbrain -text\n")
	for _, p := range reg.All() { // deterministic: sorted by name
		for _, pat := range p.Patterns() { // deterministic: table order
			if pat.Class != provider.ClassRegenerated {
				continue
			}
			fmt.Fprintf(&b, "**/%s/%s merge=agentbrain-lww\n", p.Name(), pat.Glob)
		}
	}
	b.WriteString(".gitattributes -filter -diff -merge text eol=lf\n")
	b.WriteString(".agent-brain/** -filter -diff -merge text eol=lf\n")
	return b.String()
}

// WriteAttributes atomically replaces the checkout's .gitattributes with
// the canonical content (temp file + rename; no partial-state window).
func WriteAttributes(l Layout, reg *provider.Registry) error {
	if err := renameio.WriteFile(l.AttributesFile(), []byte(GenerateAttributes(reg)), 0o644); err != nil {
		return fmt.Errorf("write attributes: %w", err)
	}
	return nil
}
